### ISSUE TITLE
Architectural diagram

### ISSUE THREAD

**Issue by obfuscurity** [graphite-project/graphite-project.github.io#9]
Something to replace http://graphite.wikidot.com/high-level-diagram.

refs #4

**Comment by obfuscurity** [comment]
https://github.com/graphite-project/graphite-web/blob/master/webapp/content/img/overview.png

![](https://raw.githubusercontent.com/graphite-project/graphite-web/master/webapp/content/img/overview.png)

**Comment by obfuscurity** [comment]
I also have the xml source from draw.io, not sure if we want to commit that somewhere.

**Comment by gwaldo** [comment]
That sounds like a fantastic idea.

**Comment by obfuscurity** [comment]
@gwaldo Any suggestions where to store it?

**Comment by gwaldo** [comment]
Right now it looks like the artifact that was produced (the image) lives in the `webapp/` directory.  Personally, I think that the image should be part of the documentation.  Since the artifact itself is part of the documentation, and the source itself exists only for documentation, I would say that the source should live with the artifact that it produces in the `docs/` directory.  It might make sense to have a `docs/images/` dir to hold the resultant image.

**Comment by gwaldo** [comment]
It just occurred to me that this is how I would organize a filesystem, but I may be completely naive with regards to how rST will react to having these files in here.

**Comment by obfuscurity** [comment]
Here's the file, feel free to add it where you think most appropriate.
https://dl.dropboxusercontent.com/u/14515229/graphite_overview.xml

**Comment by gwaldo** [comment]
Looking at this now.  Hooray for obfuscated xml... :hankey:

**Comment by gwaldo** [comment]
PR https://github.com/graphite-project/graphite-web/pull/1176
